### ISSUE TITLE
Add support for django-fsm

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#120]
[Django FSM](https://github.com/viewflow/django-fsm) is great for handling the "states" of your objects.

It also provides and option to have and "button" that will initiate the state transition. These buttons now break Django Unfold styling.

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/

**Comment by niccolox** [comment]
I am in the same situation

love unfoldadmin but need fsm admin to work, its the entire purpose of the app

I am using these more recent forks

ttps://github.com/django-commons/django-fsm-2
pip install -e git://github.com/coral-li/django-fsm-2-admin.git#egg=django-fsm-2-admin
https://github.com/jazzband/django-fsm-log

will investigate unfold further and see what I can do, otherwise will back out of unfold

**Comment by lukasvinclav** [comment]
@niccolox Please note that Unfold is an open-source project, and I unfortunately can’t provide free integration or customization services.

For commercial support or custom development, please check out my consulting services here: https://unfoldadmin.com/consulting/
