### ISSUE TITLE
Feature Request: Allow configuration for bar graph options

### ISSUE THREAD

**Issue by muhammedabad** [unfoldadmin/django-unfold#217]
In my example below, I have multiple entries per day (see `2023-12-01` as an example) that I want to display as separate bars on the graph. Can we enable support for options such as:

- Stacking
- Bar Width

I'm not sure why the y-axis labels do not show by default, is this something that also requires configuration to be added ?

![image](https://github.com/unfoldadmin/django-unfold/assets/1520135/fb449795-abd9-403a-b814-9703a76ed8fd)

Thanks in advance :)

**Comment by lukasvinclav** [comment]
When it comes to charts, it is pretty hard to create a visual which is going to look good under all circumstances. The default visual works for our demo purposes but for your use case with small amount if data it is not that visually appealing. 

I created new PR #236 which will allow you to override default styling. I recommend creating your own configuration in a view which will be send to the template.

**Comment by PaulleDemon** [comment]
Hi @lukasvinclav 

In [app.js](https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/static/unfold/js/app.js) Can you change 
```
options: options ? JSON.parse(options) : DEFAULT_CHART_OPTIONS,
```
to 
something like:
```js
options: {...DEFAULT_CHART_OPTIONS, ...JSON.parse(options)}
```

Since, This way we wont be required to write all the options, incase we'd only want to change few of the properties like just the `barThickness`, most people are likely to just change few options so I think think second would be better. Let me know your thoughts on this. 

Thanks
Paul
