### ISSUE TITLE
Invalid block tag on line 24: 'component', expected 'endblock'. Did you forget to register or load this tag? How to fix it, I want to create a new dashboard??

### ISSUE THREAD

**Issue by Muhammadali-Akbarov** [unfoldadmin/django-unfold#269]
<img width="765" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/79622590/dd3217bd-d2dd-4070-9d13-e73d5b6bcfde">

**Comment by lukasvinclav** [comment]
Would you mind to create a minimal repository where it is possible to reproduce this issue?

**Comment by marty0678** [comment]
I believe it's because the docs are missing the unfold tag load as I just encountered this too:

This section - https://github.com/unfoldadmin/django-unfold#overriding-template

Should have: `{% load cache unfold i18n %}` instead of `{% load cache humanize i18n %}` (I removed `humanize` because it's not included by default in new projects).

The unfold components section also has a small typo:

```
{% component "unfold/components/flex.html" with col=1 %}
    {% component "unfold/components/card.html" %}
        {% component "unfold/components/title.html" %}
            Card Title
        {% endcomponent %}
    {% endcomponent %}
{% endcompontent %} <---- should be endcomponent 
```

I can open a PR if you would like?

**Comment by cdavid14** [comment]
> I believe it's because the docs are missing the unfold tag load as I just encountered this too:
> 
> This section - https://github.com/unfoldadmin/django-unfold#overriding-template
> 
> Should have: `{% load cache unfold i18n %}` instead of `{% load cache humanize i18n %}` (I removed `humanize` because it's not included by default in new projects).
> 
> The unfold components section also has a small typo:
> 
> ```
> {% component "unfold/components/flex.html" with col=1 %}
>     {% component "unfold/components/card.html" %}
>         {% component "unfold/components/title.html" %}
>             Card Title
>         {% endcomponent %}
>     {% endcomponent %}
> {% endcompontent %} <---- should be endcomponent 
> ```
> 
> I can open a PR if you would like?

Please open PR, it will help alot new users (like me).
