### ISSUE TITLE
UnfoldAdminDateWidget - misplaced icons

### ISSUE THREAD

**Issue by dacodekid** [unfoldadmin/django-unfold#471]
```py
from unfold.widgets import UnfoldAdminDateWidget

class BaseUnfoldMixin:
    formfield_overrides = {
        models.TextField: {
            "widget": WysiwygWidget,
        },
        models.DateField: {
            "widget": UnfoldAdminDateWidget(
                format="%m-%d-%Y",
                attrs={
                    "placeholder": "MM-DD-YYYY",
                },
            ),
            "input_formats": ["%m-%d-%Y"],
        },
    }
```

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/991cb287-1bd1-41b1-abcb-bf9fe35d015d)

Trying to use `UnfoldAdminDateWidget` instead of [UnfoldAdminSingleDateWidget](https://github.com/unfoldadmin/django-unfold/issues/470) and noticed both icons are displaying on the top/right corner of the page.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/7013b1cd-1b2b-423c-bb4a-fadf7b9d83b9)

Apart from above, this widget also has same [issues](https://github.com/unfoldadmin/django-unfold/issues/470) as `UnfoldAdminSingleDateWidget`.

**Comment by lukasvinclav** [comment]
I don't understand the code above and especially `formfield_overrides` part. The model fields has their own widget specification in Unfold, you don't have to override the DateField because it is done in Unfold itself. If you still have the issue, please create a minimal repo where it is possible to reproduce the issue so I can see the whole codebase.

https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/admin.py#L73-L96
