### ISSUE TITLE
Support ModelAdmin.search_help_text

### ISSUE THREAD

**Issue by konkab** [unfoldadmin/django-unfold#558]
It'd be nice if we can use [ModelAdmin.search_help_text](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_help_text) as a placeholder value for search field in changelist.

**Comment by lukasvinclav** [comment]
Have you ever used this option in admin? Can you post me an example search help text which you put under the search field (screenshot appreciated)? To be honest, I'm not persuaded to add a support for this because that area is already packed and I don't want to make it even more complex from UX standpoint.

**Comment by konkab** [comment]
Here's an example:
<img width="511" alt="Screenshot 2024-07-10 at 17 35 47" src="https://github.com/unfoldadmin/django-unfold/assets/1832821/71ce637d-2464-42d1-a016-74d98f95c941">

As you can see it helps users to better understand what exactly they should enter in the search field.

I'm proposing to use it as a placeholder value for the search field or default value of "Type to search" if not provided.
