### ISSUE TITLE
Use proper "unfold" boolean icon for read-only boolean field

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#789]
**What version of Unfold are you using?**

main

**What version of Django are you using?**

5.1

**Are you able to replicate the bug in the demo site?**

No read-only boolean field there (would be great to add it)

**Describe your issue**

For read-only field default Django-style boolean icon is used instead of "unfold"

**Comment by lukasvinclav** [comment]
I just checked demo site and in same basic display of boolean fields seems okay. Would you mind to post me a link at the demo site or screenshot where this functionalit is not working?

Booleans in changelist:

https://demo.unfoldadmin.com/admin/formula/user/

Readonly booleans in changeform:

https://demo.unfoldadmin.com/admin/formula/driver/56/change/

**Comment by PavelPancocha** [comment]
@lukasvinclav Sorry Lukas, is that a regular model field? Can you link me to it?

![image](https://github.com/user-attachments/assets/59b884be-ffd1-4392-a265-e15f2ddb4a83)

I was probably not specific enough:
I have a model with the boolean field, which is read-only. It uses default Django boolean icon, not "unfold".

If needed, I will create a minimum example repo.

Thank you!

**Comment by lukasvinclav** [comment]
All examples are available in demo repository.

**Comment by tugofpeas** [comment]
@lukasvinclav seeing that @PavelPancocha fix was never merged, this is still broken...

I'm on:
django-unfold==0.63.0
Django==5.2.5

Using the following rudimentary override label for a read-only field results in the default django admin style boolean, instead of unfold-themed in changeform only. Strangely enough, changelist shows it correctly. See attached images below.

```python
readonly_fields = ('is_superuser', 'get_is_active', 'get_created_at', 'get_last_login')

@display(description=_('Active/Inactive'), boolean=True)
def get_is_active(self, instance: User):
    return instance.is_active
```

**Changeform** - Shows default "dajngo-style"
![Image](https://github.com/user-attachments/assets/be6205a2-297e-4518-ac3d-cda7127d4d95)

**Changelist** - Shows correct "unfold-themed"
![Image](https://github.com/user-attachments/assets/2bb7f510-6753-4223-838d-d3a71a9f3341)

**Comment by artamonovkirill** [comment]
+1, I have the same issue with django-unfold==0.71.0

I presume https://github.com/unfoldadmin/django-unfold/pull/790 was auto-closed because this issue has been closed, but the issue still exists.

**Comment by lukasvinclav** [comment]
@artamonovkirill if the issue is closed, reopen new one and file all important information how to reproduce it

**Comment by artamonovkirill** [comment]
👌 https://github.com/unfoldadmin/django-unfold/issues/1732 created
